# Generated by Django 6.0.6 on 2026-06-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_on_new_candidate',
            field=models.BooleanField(default=False, help_text='If on, email this client when a new candidate is shared.'),
        ),
    ]
