"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets from backend/.env (Google OAuth keys, etc.) if present.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to a dev key when DJANGO_SECRET_KEY is unset OR blank (an empty
# `DJANGO_SECRET_KEY=` line in .env counts as blank, not missing).
SECRET_KEY = (
    os.environ.get('DJANGO_SECRET_KEY')
    or 'django-insecure-)=!l$nvm$zj^#$#%bp&(=a^h)+o^o=hovg5^xx&+&e!8@x5r_o'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to OFF so production is safe by default; local dev sets DJANGO_DEBUG=true
# in backend/.env.
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() == 'true'

# Hosts allowed to serve this app. Localhost for dev; production hosts come from
# DJANGO_ALLOWED_HOSTS (comma-separated) plus Render's auto-provided hostname.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS += [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if h.strip()
]
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# The dashboard POSTs to the API. Django's CSRF protection checks the browser's
# Origin header, so the dashboard origins must be trusted for write requests
# (POST/PATCH/DELETE) to be accepted. Dev uses the Vite proxy origins; production
# origins come from CSRF_TRUSTED_ORIGINS (comma-separated) plus the Render host.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CSRF_TRUSTED_ORIGINS += [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Production hardening. Render terminates TLS at its proxy and forwards the
# original scheme in X-Forwarded-Proto, so trust that to detect HTTPS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Tell browsers to stick to HTTPS for a year (Render is HTTPS-only).
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Required by allauth for managing the current site.
    'django.contrib.sites',
    # Third-party apps
    'rest_framework',
    # Google (and other) social login.
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Local apps
    'accounts',
    'core',
]

SITE_ID = 1

# Use our custom user model (accounts.User) instead of Django's default.
# Must be set before the first migration that creates the users table.
AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework.
# Every endpoint requires a logged-in user by default (prompt requirement:
# "every endpoint must be authenticated to protect user data"). Individual
# views can opt out explicitly if ever needed. Auth is session-based for now
# (works with the browsable API and the admin login); Google OAuth is layered
# on next.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves static files (admin, DRF) efficiently in production.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Required by allauth.
    'allauth.account.middleware.AccountMiddleware',
]

# Django's default backend (username/password) plus allauth's (social login).
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level templates. Listed here (not just APP_DIRS) so our branded
        # allauth overrides take precedence over allauth's bundled templates.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses DATABASE_URL when set (Postgres in production); falls back to local SQLite
# for development so you don't need Postgres installed on your machine.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers files for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (candidate photos, company logos). Served by Django from a
# persistent disk (see config/urls.py); proxied through the Vite dev server at
# /media in development.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# In production this same Django service also serves the built React dashboard
# (dashboard/dist), so the API and UI share one origin and session-cookie auth
# "just works". WhiteNoise serves the built files at the site root; a catch-all
# route in config/urls.py returns index.html for client-side routes. In dev the
# folder doesn't exist (the Vite dev server handles the UI), so this is skipped.
FRONTEND_DIST = BASE_DIR.parent / 'dashboard' / 'dist'
if FRONTEND_DIST.is_dir():
    WHITENOISE_ROOT = FRONTEND_DIST
    WHITENOISE_INDEX_FILE = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Authentication / allauth (Google login) ---------------------------------

# Log in with email (no separate username needed for social users).
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_EMAIL_VERIFICATION = 'none'

# One-click sign out: a GET to /accounts/logout/ logs the user out immediately
# instead of rendering a confirmation page (the dashboard's "Sign out" is a link).
ACCOUNT_LOGOUT_ON_GET = True

# Email delivery. allauth sends mail during the email login flow, so an email
# backend must be reachable or the request errors out. In dev we print emails to
# the runserver console; in production set EMAIL_* env vars to use real SMTP.
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ['EMAIL_HOST']
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@antheatalent.com')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'no-reply@antheatalent.com'

# Where to send users after logging in / out. In dev this points at the React
# dashboard (http://127.0.0.1:5173/); in production set FRONTEND_URL to the
# deployed dashboard. Falls back to '/' if unset.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://127.0.0.1:5173/')
LOGIN_REDIRECT_URL = FRONTEND_URL
ACCOUNT_LOGOUT_REDIRECT_URL = FRONTEND_URL

# Anyone signing in with a Google email at this domain becomes an admin;
# everyone else is a client. Configurable via env for other environments.
ADMIN_EMAIL_DOMAIN = os.environ.get('ADMIN_EMAIL_DOMAIN', 'antheatalent.com')
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAccountAdapter'

# One-click Google sign in: a GET to /accounts/google/login/ redirects straight
# to Google's account chooser instead of showing allauth's "Continue" hand-off
# page (the dashboard's "Continue with Google" is a link).
SOCIALACCOUNT_LOGIN_ON_GET = True

# When we invite a client, we pre-create their account (with a verified email)
# and add them to a company. These let their Google sign-in attach to that
# existing account by matching the verified email, instead of erroring or making
# a second account — so an invited client lands straight in their portal.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# Google OAuth credentials come from backend/.env (never commit real values).
# See .env.example for the variable names, and the setup guide for how to get
# them from the Google Cloud Console.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [
            {
                'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
                'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
                'key': '',
            }
        ],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
