# Generated by Django 6.0.6 on 2026-06-26 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, help_text='Current/most recent role, e.g. "Senior Designer".', max_length=200)),
                ('resume_url', models.URLField(blank=True, help_text='Link to the resume (Google Drive, Dropbox, etc.).')),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('intake_notes', models.TextField(blank=True, help_text='Intake info / internal notes about the candidate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='Link to the company logo.')),
                ('point_of_contact', models.CharField(blank=True, help_text='Main contact name at the company.', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('roles', models.TextField(blank=True, help_text='Roles they are hiring for / what they are looking for.')),
                ('scheduling_link', models.URLField(blank=True, help_text='Calendly / Cal.com link for booking meetings.')),
                ('intake_link', models.URLField(blank=True, help_text='Intake form link.')),
                ('status', models.CharField(choices=[('needs_candidates', 'Needs candidates'), ('reviewing', 'Reviewing'), ('paused', 'Paused'), ('placed', 'Placed')], default='needs_candidates', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Client users who can log in and see this company.', related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('shared', 'Shared (awaiting client review)'), ('passed', 'Passed'), ('accepted', 'Accepted'), ('meeting', 'Meeting booked'), ('interviewing', 'Interviewing'), ('placed', 'Placed')], default='shared', max_length=20)),
                ('pass_feedback', models.TextField(blank=True, help_text='If the client passed, why. Shown to admin only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'company'), name='unique_candidate_company')],
            },
        ),
    ]
