# Generated by Django 6.0.6 on 2026-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about',
            field=models.TextField(blank=True, help_text="Candidate's own summary. Shown to clients."),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('0-2', '0–2 years'), ('3+', '3+ years')], help_text='Experience level (matches the marketing intake form).', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role_wanted',
            field=models.CharField(blank=True, help_text='Role they want next, e.g. "Growth Marketing".', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='intake_notes',
            field=models.TextField(blank=True, help_text='Intake info / internal notes about the candidate. Admin only.'),
        ),
    ]
