# Generated by Django 6.0.6 on 2026-06-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidate_about_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo.', null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Uploaded company logo.', null=True, upload_to='companies/'),
        ),
    ]
