# Generated by Django 6.0.6 on 2026-06-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidate_photo_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='openings',
            field=models.PositiveIntegerField(blank=True, help_text='Number of open roles / hires the company wants to fill.', null=True),
        ),
    ]
