# Generated by Django 6.0.6 on 2026-06-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_openings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers sort first in pickers.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('intern', 'Intern'), ('new_grad', 'New grad')], help_text='Stage: Student, Intern, or New grad.', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, help_text='Current/most recent role, e.g. "Marketing Intern at Acme".', max_length=200),
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Growth Intern at Acme" or "President, Marketing Club".', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional one-line detail.', max_length=300)),
                ('url', models.URLField(blank=True, help_text='Optional link to their work.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.candidate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, help_text='Focus-area tags shown as chips (e.g. Growth, Social media).', related_name='candidates', to='core.tag'),
        ),
    ]
